name: Release

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*' # Trigger on tags like v1.0.0
  pull_request:
    branches:
      - main
      - master
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Create and push tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: 'v1.1.1' # Specify the tag name you want to create
          release_name: '1.0.0' # Name of the existing release you want to link the tag to
          body: |
            Changes in this release:
            - Describe your changes here
          draft: false
          prerelease: false
          commitish: ${{ github.sha }} # Optionally specify the commit SHA to tag
